### ISSUE TITLE
1.3 bug report + fabric

### ISSUE THREAD

**Issue by CaptainTemerin** [47MarkIV/Project-SeaTech#2]
just installed the mod pack 
1} fabric api made it into the list

2) you cant eat right clicking with food dose zip

**Comment by CharZinta** [comment]
Fabric API was mistakenly added during deathchest update. This will be fixed in the next release. Pleaase provide more details on #2.

**Comment by CaptainTemerin** [comment]
no matter what food item you try to eat pressing right mouse dose nothing you can brake blocks why apple etc

**Comment by CaptainTemerin** [comment]
updated to the latest 1.3.1 and its working fine very odd many thank :)

**Comment by CharZinta** [comment]
Thank you for reporting everything.  Please enjoy.
